# Generated by Django 6.1.1 on 2026-09-07 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaiverity',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
