# Generated by Django 6.1 on 2026-09-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chair_verity',
            new_name='chair_verities',
        ),
    ]
