# Generated by Django 6.1 on 2026-09-16 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_rename_chair_verity_store_chair_verities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='chair_verities',
            new_name='chai_verities',
        ),
    ]
